export const VENUES = {
  restauracia: {
    slug: 'restauracia',
    label: 'Reštaurácia',
    tagline: 'Originálna pizza, tradičné jedlá a letná terasa',
    heroImage: '/photos/restauracia-mp.jpg',
    photos: [
      '/photos/restauracia.jpg',
      '/photos/restauracia-1.jpg',
      '/photos/restauracia-2.jpg',
      '/photos/restauracia-3.jpg',
      '/photos/restauracia-4.jpg',
    ],
    hoursText: 'Po–Št 10:30–22:00 · Pi 10:30–24:00 · So 12:00–24:00 · Ne 12:00–22:00',
    description:
      'Príjemné prostredie s pestrým jedálnym lístkom - nájdete u nás originálnu pizzu aj tradičné jedlá, každý deň aj obedové menu. Reštaurácia pojme až 80 osôb a v lete je k dispozícii rozľahlá terasa. Radi pre vás zorganizujeme aj rodinné oslavy či firemné akcie.',
    contactNote: 'Objednávky a prevádzka: 038/760 74 44 · Spoločenské akcie: 0915 450 996 (Bianka Podlucká)',
    hasReservation: false,
  },
  fitness: {
    slug: 'fitness',
    label: 'Fitness',
    tagline: 'Posilňovňa pre všetky úrovne',
    heroImage: '/photos/fitness-mp.jpg',
    photos: ['/photos/fitness-1.jpg', '/photos/fitness-2.jpg', '/photos/fitness-3.jpg'],
    hoursText: 'Po–Pi 09:00–20:00 · So zatvorené · Ne a sviatky 09:00–14:30',
    priceInfo: 'Jednorázový vstup 2,50 € · Permanentka na 10 vstupov 22,50 €',
    description:
      'Fitness centrum HARI ponúka kompletné vybavenie na posilňovanie aj kardio tréning. Vstup je možný jednorázovo alebo výhodnejšie na permanentku.',
    contactNote: 'Manažérka Eva Hanáková · info na 0915 450 996',
    hasReservation: false,
    hasDefectReport: true,
  },
  bowling: {
    slug: 'bowling',
    label: 'Bowling',
    tagline: 'Bowlingové dráhy pre priateľov aj oslavy',
    heroImage: '/photos/bowling-mp.jpg',
    photos: ['/photos/bowling.jpg'],
    hoursText: 'Po–Št 10:00–22:00 · Pi 10:00–24:00 · So 12:00–24:00 · Ne a sviatky 12:00–22:00',
    priceInfo: '12 € / hod za dráhu',
    description:
      'Zahrajte si bowling v príjemnom prostredí športcentra HARI. Zapožičanie špeciálnej bowlingovej obuvi je v cene zadarmo. Termín si môžete rezervovať online nižšie, alebo telefonicky.',
    contactNote: 'Prevádzkovateľ: Richard Hanák',
    resourceId: 'bowling',
    hasReservation: true,
  },
  'tenisova-hala': {
    slug: 'tenisova-hala',
    label: 'Tenisová hala',
    tagline: 'Kryté kurty s povrchom gerflor a taraflex',
    heroImage: '/photos/tenis-hala-mp.jpg',
    photos: ['/photos/tenis-hala.jpg'],
    hoursText: 'Po–Ne 08:00–22:00',
    priceInfo: 'Letná sezóna (1.5.–30.9.) 10 € / hod · Zimná sezóna (1.10.–30.4.) 12 € / hod',
    description:
      'Tenisová hala s kvalitným povrchom gerflor a taraflex je k dispozícii celoročne. V hale si môžete dokúpiť loptičky, gripy alebo využiť službu vypletania rakiet.',
    contactNote: 'Prevádzkovateľ: Richard Hanák',
    resourceId: 'tenisova-hala',
    hasReservation: true,
  },
  'tenisovy-kurt': {
    slug: 'tenisovy-kurt',
    label: 'Tenisový kurt',
    tagline: 'Vonkajší antukový kurt',
    heroImage: '/photos/tenis-kurt.jpg',
    photos: ['/photos/tenis-kurt.jpg'],
    hoursText: 'Po–Ne 08:00–21:30',
    priceInfo: '8 € / hod · 6 € / hod pre členov ŠK M-R Tenis club · šatňa a sprchy v cene',
    description:
      'Vonkajší tenisový kurt s antukovým povrchom, k dispozícii je šatňa a sprchy v cene prenájmu.',
    contactNote: 'Prevádzkovateľ: M-R Tennis club',
    resourceId: 'tenisovy-kurt',
    hasReservation: true,
  },
  badminton: {
    slug: 'badminton',
    label: 'Badminton',
    tagline: 'Dva kurty v tenisovej hale',
    heroImage: '/photos/badminton-1.jpg',
    photos: ['/photos/badminton-1.jpg', '/photos/badminton-2.jpg'],
    hoursText: 'Po–Ne 08:00–22:00',
    priceInfo: 'Letná sezóna (1.5.–30.9.) 10 € / hod · Zimná sezóna (1.10.–30.4.) 12 € / hod',
    description: 'Badminton sa hrá na 2 kurtoch priamo v tenisovej hale.',
    contactNote: 'Prevádzkovateľka: Eva Hanáková',
    resourceId: 'badminton',
    hasReservation: true,
  },
};

export const VENUE_LIST = Object.values(VENUES);
