app = "hari-sportcentrum-api"
primary_region = "waw"

[build]

[env]
  PORT = "5001"
  DB_PATH = "/data/hari.db"

[[mounts]]
  source = "hari_data"
  destination = "/data"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
